import 'package:country_flags/country_flags.dart';
import 'package:flutter/material.dart';

class Getflagpays {
  static Map<String, String> countries = {
    "afghanistan": "AF",
    "albanie": "AL",
    "algérie": "DZ",
    "andorre": "AD",
    "angola": "AO",
    "antigua-et-barbuda": "AG",
    "argentine": "AR",
    "arménie": "AM",
    "australie": "AU",
    "autriche": "AT",
    "azerbaïdjan": "AZ",
    "bahamas": "BS",
    "bahreïn": "BH",
    "bangladesh": "BD",
    "barbade": "BB",
    "biélorussie": "BY",
    "belgique": "BE",
    "belize": "BZ",
    "bénin": "BJ",
    "bhoutan": "BT",
    "bolivie": "BO",
    "bosnie-herzégovine": "BA",
    "botswana": "BW",
    "brésil": "BR",
    "brunei": "BN",
    "bulgarie": "BG",
    "burkina faso": "BF",
    "burundi": "BI",
    "cambodge": "KH",
    "cameroun": "CM",
    "canada": "CA",
    "cap-vert": "CV",
    "république centrafricaine": "CF",
    "tchad": "TD",
    "chili": "CL",
    "chine": "CN",
    "colombie": "CO",
    "comores": "KM",
    "congo (brazzaville)": "CG",
    "congo (kinshasa)": "CD",
    "costa rica": "CR",
    "côte d'ivoire": "CI",
    "croatie": "HR",
    "cuba": "CU",
    "chypre": "CY",
    "république tchèque": "CZ",
    "danemark": "DK",
    "djibouti": "DJ",
    "dominique": "DM",
    "république dominicaine": "DO",
    "équateur": "EC",
    "égypte": "EG",
    "el salvador": "SV",
    "guinée équatoriale": "GQ",
    "érythrée": "ER",
    "estonie": "EE",
    "éthiopie": "ET",
    "fidji": "FJ",
    "finlande": "FI",
    "france": "FR",
    "gabon": "GA",
    "gambie": "GM",
    "géorgie": "GE",
    "allemagne": "DE",
    "ghana": "GH",
    "grèce": "GR",
    "grenade": "GD",
    "guatemala": "GT",
    "guinée": "GN",
    "guinée-bissau": "GW",
    "guyana": "GY",
    "haïti": "HT",
    "honduras": "HN",
    "hongrie": "HU",
    "islande": "IS",
    "inde": "IN",
    "indonésie": "ID",
    "iran": "IR",
    "irak": "IQ",
    "irlande": "IE",
    "israël": "IL",
    "italie": "IT",
    "jamaïque": "JM",
    "japon": "JP",
    "jordanie": "JO",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "kiribati": "KI",
    "corée du nord": "KP",
    "corée du sud": "KR",
    "koweït": "KW",
    "kirghizistan": "KG",
    "laos": "LA",
    "lettonie": "LV",
    "liban": "LB",
    "lesotho": "LS",
    "libéria": "LR",
    "libye": "LY",
    "liechtenstein": "LI",
    "lituanie": "LT",
    "luxembourg": "LU",
    "macédoine": "MK",
    "madagascar": "MG",
    "malawi": "MW",
    "malaisie": "MY",
    "maldives": "MV",
    // "mali": "ML",
    "malte": "MT",
    "îles marshall": "MH",
    "mauritanie": "MR",
    "maurice": "MU",
    "mexique": "MX",
    "micronésie": "FM",
    "moldavie": "MD",
    "monaco": "MC",
    "mongolie": "MN",
    "monténégro": "ME",
    "maroc": "MA",
    "mozambique": "MZ",
    "birmanie": "MM",
    "namibie": "NA",
    "nauru": "NR",
    "népal": "NP",
    "pays-bas": "NL",
    "nouvelle-zélande": "NZ",
    "nicaragua": "NI",
    "niger": "NE",
    "nigeria": "NG",
    "niué": "NU",
    "norvège": "NO",
    "oman": "OM",
    "pakistan": "PK",
    "palaos": "PW",
    "palestine": "PS",
    "panama": "PA",
    "papouasie-nouvelle-guinée": "PG",
    "paraguay": "PY",
    "pérou": "PE",
    "philippines": "PH",
    "pologne": "PL",
    "portugal": "PT",
    "qatar": "QA",
    "roumanie": "RO",
    "russie": "RU",
    "rwanda": "RW",
    "saint-kitts-et-nevis": "KN",
    "sainte-lucie": "LC",
    "saint-vincent-et-les-grenadines": "VC",
    "samoa": "WS",
    "saint-marin": "SM",
    "sao tomé-et-principe": "ST",
    "arabie saoudite": "SA",
    "sénégal": "SN",
    "serbie": "RS",
    "seychelles": "SC",
    "sierra leone": "SL",
    "singapour": "SG",
    "slovaquie": "SK",
    "slovénie": "SI",
    "salomon": "SB",
    "somalie": "SO",
    "afrique du sud": "ZA",
    "soudan du sud": "SS",
    "espagne": "ES",
    "sri lanka": "LK",
    "soudan": "SD",
    "suriname": "SR",
    "swaziland": "SZ",
    "suède": "SE",
    "suisse": "CH",
    "syrie": "SY",
    "tadjikistan": "TJ",
    "tanzanie": "TZ",
    "thaïlande": "TH",
    "timor oriental": "TL",
    "togo": "TG",
    "tonga": "TO",
    "trinité-et-tobago": "TT",
    "tunisie": "TN",
    "turquie": "TR",
    "turkménistan": "TM",
    "tuvalu": "TV",
    "ouganda": "UG",
    "ukraine": "UA",
    "émirats arabes unis": "AE",
    "royaume-uni": "GB",
    "états-unis": "US",
    "uruguay": "UY",
    "ouzbékistan": "UZ",
    "vanuatu": "VU",
    "vatican": "VA",
    "vénézuéla": "VE",
    "vietnam": "VN",
    "yémen": "YE",
    "zambie": "ZM",
    "zimbabwe": "ZW",
    "united states": "ML",
  };

  static Widget getFlag(String pays) {
    String code = '';
    String p = pays.toLowerCase();
    countries.forEach((key, value) {
      if (p == key) {
        code = value;
      }
    });
    return CountryFlag.fromCountryCode(
      code,
      height: 30,
      width: 30,
    );
  }
}
