import 'package:country_flags/country_flags.dart';
import 'package:flutter/material.dart';

class CodePays {
  Map<String, String> countries = {
    "afghanistan": "AF",
    "albanie": "AL",
    "algérie": "DZ",
    "andorre": "AD",
    "angola": "AO",
    "antigua-et-barbuda": "AG",
    "argentine": "AR",
    "arménie": "AM",
    "australie": "AU",
    "autriche": "AT",
    "azerbaïdjan": "AZ",
    "bahamas": "BS",
    "bahreïn": "BH",
    "bangladesh": "BD",
    "barbade": "BB",
    "biélorussie": "BY",
    "belgique": "BE",
    "belize": "BZ",
    "bénin": "BJ",
    "bhoutan": "BT",
    "bolivie": "BO",
    "bosnie-herzégovine": "BA",
    "botswana": "BW",
    "brésil": "BR",
    "brunei": "BN",
    "bulgarie": "BG",
    "burkina faso": "BF",
    "burundi": "BI",
    "cambodge": "KH",
    "cameroun": "CM",
    "canada": "CA",
    "cap-vert": "CV",
    "république centrafricaine": "CF",
    "tchad": "TD",
    "chili": "CL",
    "chine": "CN",
    "colombie": "CO",
    "comores": "KM",
    "congo (brazzaville)": "CG",
    "congo (kinshasa)": "CD",
    "costa rica": "CR",
    "côte d'ivoire": "CI",
    "croatie": "HR",
    "cuba": "CU",
    "chypre": "CY",
    "république tchèque": "CZ",
    "danemark": "DK",
    "djibouti": "DJ",
    "dominique": "DM",
    "république dominicaine": "DO",
    "équateur": "EC",
    "égypte": "EG",
    "el salvador": "SV",
    "guinée équatoriale": "GQ",
    "érythrée": "ER",
    "estonie": "EE",
    "éthiopie": "ET",
    "fidji": "FJ",
    "finlande": "FI",
    "france": "FR",
    "gabon": "GA",
    "gambie": "GM",
    "géorgie": "GE",
    "allemagne": "DE",
    "ghana": "GH",
    "grèce": "GR",
    "grenade": "GD",
    "guatemala": "GT",
    "guinée": "GN",
    "guinée-bissau": "GW",
    "guyana": "GY",
    "haïti": "HT",
    "honduras": "HN",
    "hongrie": "HU",
    "islande": "IS",
    "inde": "IN",
    "indonésie": "ID",
    "iran": "IR",
    "irak": "IQ",
    "irlande": "IE",
    "israël": "IL",
    "italie": "IT",
    "jamaïque": "JM",
    "japon": "JP",
    "jordanie": "JO",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "kiribati": "KI",
    "corée du nord": "KP",
    "corée du sud": "KR",
    "koweït": "KW",
    "kirghizistan": "KG",
    "laos": "LA",
    "lettonie": "LV",
    "liban": "LB",
    "lesotho": "LS",
    "libéria": "LR",
    "libye": "LY",
    "liechtenstein": "LI",
    "lituanie": "LT",
    "luxembourg": "LU",
    "macédoine": "MK",
    "madagascar": "MG",
    "malawi": "MW",
    "malaisie": "MY",
    "maldives": "MV",
    "mali": "ML",
    "malte": "MT",
    "îles marshall": "MH",
    "mauritanie": "MR",
    "maurice": "MU",
    "mexique": "MX",
    "micronésie": "FM",
    "moldavie": "MD",
    "monaco": "MC",
    "mongolie": "MN",
    "monténégro": "ME",
    "maroc": "MA",
    "mozambique": "MZ",
    "birmanie": "MM",
    "namibie": "NA",
    "nauru": "NR",
    "népal": "NP",
    "pays-bas": "NL",
    "nouvelle-zélande": "NZ",
    "nicaragua": "NI",
    "niger": "NE",
    "nigeria": "NG",
    "niué": "NU",
    "norvège": "NO",
    "oman": "OM",
    "pakistan": "PK",
    "palaos": "PW",
    "palestine": "PS",
    "panama": "PA",
    "papouasie-nouvelle-guinée": "PG",
    "paraguay": "PY",
    "pérou": "PE",
    "philippines": "PH",
    "pologne": "PL",
    "portugal": "PT",
    "qatar": "QA",
    "roumanie": "RO",
    "russie": "RU",
    "rwanda": "RW",
    "saint-kitts-et-nevis": "KN",
    "sainte-lucie": "LC",
    "saint-vincent-et-les-grenadines": "VC",
    "samoa": "WS",
    "saint-marin": "SM",
    "sao tomé-et-principe": "ST",
    "arabie saoudite": "SA",
    "sénégal": "SN",
    "serbie": "RS",
    "seychelles": "SC",
    "sierra leone": "SL",
    "singapour": "SG",
    "slovaquie": "SK",
    "slovénie": "SI",
    "salomon": "SB",
    "somalie": "SO",
    "afrique du sud": "ZA",
    "soudan du sud": "SS",
    "espagne": "ES",
    "sri lanka": "LK",
    "soudan": "SD",
    "suriname": "SR",
    "swaziland": "SZ",
    "suède": "SE",
    "suisse": "CH",
    "syrie": "SY",
    "tadjikistan": "TJ",
    "tanzanie": "TZ",
    "thaïlande": "TH",
    "timor oriental": "TL",
    "togo": "TG",
    "tonga": "TO",
    "trinité-et-tobago": "TT",
    "tunisie": "TN",
    "turquie": "TR",
    "turkménistan": "TM",
    "tuvalu": "TV",
    "ouganda": "UG",
    "ukraine": "UA",
    "émirats arabes unis": "AE",
    "royaume-uni": "GB",
    "united states": "US",
    "uruguay": "UY",
    "ouzbékistan": "UZ",
    "vanuatu": "VU",
    "vatican": "VA",
    "vénézuéla": "VE",
    "vietnam": "VN",
    "yémen": "YE",
    "zambie": "ZM",
    "zimbabwe": "ZW",
  };

 Map<String, String> countrie = {
  "afghanistan": "AF",
  "albania": "AL",
  "algeria": "DZ",
  "andorra": "AD",
  "angola": "AO",
  "antigua and barbuda": "AG",
  "argentina": "AR",
  "armenia": "AM",
  "australia": "AU",
  "austria": "AT",
  "azerbaijan": "AZ",
  "bahamas": "BS",
  "bahrain": "BH",
  "bangladesh": "BD",
  "barbados": "BB",
  "belarus": "BY",
  "belgium": "BE",
  "belize": "BZ",
  "benin": "BJ",
  "bhutan": "BT",
  "bolivia": "BO",
  "bosnia and herzegovina": "BA",
  "botswana": "BW",
  "brazil": "BR",
  "brunei": "BN",
  "bulgaria": "BG",
  "burkina faso": "BF",
  "burundi": "BI",
  "cambodia": "KH",
  "cameroon": "CM",
  "canada": "CA",
  "cape verde": "CV",
  "central african republic": "CF",
  "chad": "TD",
  "chile": "CL",
  "china": "CN",
  "colombia": "CO",
  "comoros": "KM",
  "congo (brazzaville)": "CG",
  "congo (kinshasa)": "CD",
  "costa rica": "CR",
  "ivory coast": "CI",
  "croatia": "HR",
  "cuba": "CU",
  "cyprus": "CY",
  "czech republic": "CZ",
  "denmark": "DK",
  "djibouti": "DJ",
  "dominica": "DM",
  "dominican republic": "DO",
  "ecuador": "EC",
  "egypt": "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  "eritrea": "ER",
  "estonia": "EE",
  "ethiopia": "ET",
  "fiji": "FJ",
  "finland": "FI",
  "france": "FR",
  "gabon": "GA",
  "gambia": "GM",
  "georgia": "GE",
  "germany": "DE",
  "ghana": "GH",
  "greece": "GR",
  "grenada": "GD",
  "guatemala": "GT",
  "guinea": "GN",
  "guinea-bissau": "GW",
  "guyana": "GY",
  "haiti": "HT",
  "honduras": "HN",
  "hungary": "HU",
  "iceland": "IS",
  "india": "IN",
  "indonesia": "ID",
  "iran": "IR",
  "iraq": "IQ",
  "ireland": "IE",
  "israel": "IL",
  "italy": "IT",
  "jamaica": "JM",
  "japan": "JP",
  "jordan": "JO",
  "kazakhstan": "KZ",
  "kenya": "KE",
  "kiribati": "KI",
  "north korea": "KP",
  "south korea": "KR",
  "kuwait": "KW",
  "kyrgyzstan": "KG",
  "laos": "LA",
  "latvia": "LV",
  "lebanon": "LB",
  "lesotho": "LS",
  "liberia": "LR",
  "libya": "LY",
  "liechtenstein": "LI",
  "lithuania": "LT",
  "luxembourg": "LU",
  "macedonia": "MK",
  "madagascar": "MG",
  "malawi": "MW",
  "malaysia": "MY",
  "maldives": "MV",
  "mali": "ML",
  "malta": "MT",
  "marshall islands": "MH",
  "mauritania": "MR",
  "mauritius": "MU",
  "mexico": "MX",
  "micronesia": "FM",
  "moldova": "MD",
  "monaco": "MC",
  "mongolia": "MN",
  "montenegro": "ME",
  "morocco": "MA",
  "mozambique": "MZ",
  "myanmar": "MM",
  "namibia": "NA",
  "nauru": "NR",
  "nepal": "NP",
  "netherlands": "NL",
  "new zealand": "NZ",
  "nicaragua": "NI",
  "niger": "NE",
  "nigeria": "NG",
  "niue": "NU",
  "norway": "NO",
  "oman": "OM",
  "pakistan": "PK",
  "palau": "PW",
  "palestine": "PS",
  "panama": "PA",
  "papua new guinea": "PG",
  "paraguay": "PY",
  "peru": "PE",
  "philippines": "PH",
  "poland": "PL",
  "portugal": "PT",
  "qatar": "QA",
  "romania": "RO",
  "russia": "RU",
  "rwanda": "RW",
  "saint kitts and nevis": "KN",
  "saint lucia": "LC",
  "saint vincent and the grenadines": "VC",
  "samoa": "WS",
  "san marino": "SM",
  "sao tome and principe": "ST",
  "saudi arabia": "SA",
  "senegal": "SN",
  "serbia": "RS",
  "seychelles": "SC",
  "sierra leone": "SL",
  "singapore": "SG",
  "slovakia": "SK",
  "slovenia": "SI",
  "solomon islands": "SB",
  "somalia": "SO",
  "south africa": "ZA",
  "south sudan": "SS",
  "spain": "ES",
  "sri lanka": "LK",
  "sudan": "SD",
  "suriname": "SR",
  "eswatini": "SZ",
  "sweden": "SE",
  "switzerland": "CH",
  "syria": "SY",
  "tajikistan": "TJ",
  "tanzania": "TZ",
  "thailand": "TH",
  "timor-leste": "TL",
  "togo": "TG",
  "tonga": "TO",
  "trinidad and tobago": "TT",
  "tunisia": "TN",
  "turkey": "TR",
  "turkmenistan": "TM",
  "tuvalu": "TV",
  "uganda": "UG",
  "ukraine": "UA",
  "united arab emirates": "AE",
  "united kingdom": "GB",
  "united states": "US",
  "uruguay": "UY",
  "uzbekistan": "UZ",
  "vanuatu": "VU",
  "vatican": "VA",
  "venezuela": "VE",
  "vietnam": "VN",
  "yemen": "YE",
  "zambia": "ZM",
  "zimbabwe": "ZW",
};

  Widget getFlag(String pays) {
    String code = '';
    String p = pays.toLowerCase();
    countries.forEach((key, value) {
      if (p == key) {
        // setState(() {

        // });
        code = value;
      }
    });
    return code.isEmpty
        ? Image.asset(
            "assets/images/sous.png",
            width: 50,
            height: 50,
          )
        : CountryFlag.fromCountryCode(
            code,
            height: 48,
            width: 62,
          );
  }

  Widget getFlags(String pays) {
    String code = '';
    String p = pays.toLowerCase();
    countries.forEach((key, value) {
      if (p == key) {
        code = value;
      }
    });
    return code.isEmpty
        ? Text("Pays non trouvé",
            style: TextStyle(
                overflow: TextOverflow.ellipsis,
                fontSize: 15,
                fontStyle: FontStyle.italic))
        : CountryFlag.fromCountryCode(
            code,
            height: 25,
            width: 25,
          );
  }

  // Widget getFlagsApp(String pays) {
  //   String code = '';
  //   String p = pays.toLowerCase();
  //   countries.forEach((key, value) {
  //     if (p == key) {
  //       code = value;
  //     }
  //   });
  //   return CountryFlag.fromCountryCode(
  //           code,
  //           height: 20,
  //           width: 20,
  //         );
  // }

  Widget getFlagsApp(String pays) {
  // Convertir le nom du pays en minuscule pour correspondre aux clés du dictionnaire
  String p = pays.toLowerCase();
  
  // Rechercher le code du pays correspondant
  String? code = countries[p];

  // Si un code de pays est trouvé, retourner le widget CountryFlag
  if (code != null && code.isNotEmpty) {
    return CountryFlag.fromCountryCode(
      code,
      height: 20,
      width: 20,
    );
  } else {
    // Si le code de pays n'est pas trouvé, retourner un widget par défaut (par exemple, un conteneur vide ou un texte)
    return Container(); // ou Text("Drapeau non disponible");
  }
}

}
